name: Deploy to Cloudflare Pages

on:
  push:
    branches: [master, main]
    paths:
      - "web/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: e064dd3a4979759632ecf254bae8d30b
          command: pages deploy web --project-name jarvis --branch main
